const AppConfig = {
    idioma: 'pt' 
};

const Diccionario = {
    es: {
        estudiante: "Estudiante:",
        logout: "Cerrar sesión",
        bienvenidaTitulo: "Selecciona un ejercicio",
        bienvenidaDesc: "Haz clic en un ejercicio del menú lateral para ver las métricas y habilitar el tutor IA.",
        btnResolver: "Resolver Ejercicio",
        dificultad: "Nivel de dificultad:",
        promedioNota: "Calificación promedio",
        promedioTiempo: "Tiempo empleado promedio",
        analiticas: "Analíticas del ejercicio",
        sinDatos: "Aún no hay datos suficientes para este ejercicio.",
        tituloChat: "Tutor IA",
		botSaludo: "¡Hola! Soy tu tutor. ¿Tienes dudas sobre el concepto de '{concepto}'?",
        placeholderChat: "Escribe tu duda...",
        btnEnviarChat: "Enviar",
        puntos: "puntos",
        puntajeMaximo: "Puntaje Máximo:",
        btnEnviarRespuesta: "Enviar Respuesta",
        confirmarResolver: "¿Estás seguro de querer resolver el ejercicio ahora? No podrás consultar las estadísticas ni pedirle ayuda al Tutor IA.",
        alertaSeleccion: "Por favor, selecciona una opción antes de enviar.",
        alertaTexto: "Por favor, escribe tu procedimiento antes de enviar.",
        alertaExito: "¡Respuesta guardada con éxito!",
        alertaError: "Hubo un error guardando la respuesta. Inténtalo de nuevo.",
        enviando: "Enviando...",
        chartNotasTitulo: "Distribución de Notas",
        chartNotasY: "Nº de Estudiantes",
        chartNotasX: "Calificación",
        chartExitoTitulo: "Tasa de Éxito Global",
        chartAprobados: "Aprobados",
        chartSuspendidos: "Suspendidos",
        chartTiempoTitulo: "Esfuerzo vs Resultado (Tiempo en mins vs Nota)",
        chartTiempoX: "Tiempo empleado (Segundos)",
        chartTiempoY: "Nota obtenida",
        tooltipTiempo: "Tiempo",
        tooltipNota: "Nota",
        difFacil: "Fácil",
        difMedio: "Medio",
        difDificil: "Difícil",
        placeholderCalculo: "Escribe aquí todo tu procedimiento paso a paso y el resultado final...",palabraEjercicio: "Ejercicio",
        labelInteraccion: "Interacción del estudiante",
		loginTitulo: "Ingresar al Experimento",
        loginInstruccion: "Introduce tu código de estudiante:",
        loginPlaceholder: "Ej: 100456789",
        loginBoton: "Entrar",
        loginAlerta: "Por favor, ingresa tu código.",
		loginTituloPagina: "Login - Experimento Educativo",
		botPensando: "El tutor está pensando...",
		labelJustificacion: "Justificación:",
        placeholderJustificacion: "Escribe brevemente por qué has elegido esta opción...",
        alertaJustificacion: "Por favor, justifica tu respuesta antes de enviar.",
		cuadranteEficiente: "Eficiente",
        cuadrantePerseverante: "Perseverante",
        cuadranteDescuidado: "Descuidado",
        cuadrantePeligro: "Riesgo",
		chartCuadrantesTitulo: "Matriz de Esfuerzo vs Resultado",
    },
    en: {
        estudiante: "Student:",
        logout: "Log out",
        bienvenidaTitulo: "Select an exercise",
        bienvenidaDesc: "Click on an exercise from the sidebar to view metrics and enable the AI tutor.",
        btnResolver: "Solve Exercise",
        dificultad: "Difficulty level:",
        promedioNota: "Average score",
        promedioTiempo: "Average time spent",
        analiticas: "Exercise Analytics",
        sinDatos: "Not enough data for this exercise yet.",
        tituloChat: "AI Tutor",
        botSaludo: "Hi! I'm your tutor. Do you have any questions about the concept of '{concepto}'?",
        placeholderChat: "Type your question...",
        btnEnviarChat: "Send",
        puntos: "points",
        puntajeMaximo: "Max Score:",
        btnEnviarRespuesta: "Submit Answer",
        confirmarResolver: "Are you sure you want to solve the exercise now? You will not be able to check the statistics or ask the AI Tutor for help.",
        alertaSeleccion: "Please select an option before submitting.",
        alertaTexto: "Please write your procedure before submitting.",
        alertaExito: "Answer saved successfully!",
        alertaError: "There was an error saving your answer. Please try again.",
        enviando: "Sending...",
        chartNotasTitulo: "Grade Distribution",
        chartNotasY: "Nº of Students",
        chartNotasX: "Grade",
        chartExitoTitulo: "Global Success Rate",
        chartAprobados: "Passed",
        chartSuspendidos: "Failed",
        chartTiempoTitulo: "Effort vs Result (Time in mins vs Grade)",
        chartTiempoX: "Time spent (Seconds)",
        chartTiempoY: "Grade obtained",
        tooltipTiempo: "Time",
        tooltipNota: "Grade",
        difFacil: "Easy",
        difMedio: "Medium",
        difDificil: "Hard",
        placeholderCalculo: "Write all your step-by-step procedure and final result here...",
		palabraEjercicio: "Exercise",
		labelInteraccion: "Student interaction",
		loginTitulo: "Enter the Experiment",
        loginInstruccion: "Enter your student code:",
        loginPlaceholder: "e.g., 100456789",
        loginBoton: "Log in",
        loginAlerta: "Please enter your code.",
		loginTituloPagina: "Login - Educational Experiment",
		botPensando: "The tutor is thinking...",
		labelJustificacion: "Justification:",
        placeholderJustificacion: "Briefly explain why you chose this option...",
        alertaJustificacion: "Please justify your answer before submitting.",
		cuadranteEficiente: "Efficient",
        cuadrantePerseverante: "Persistent",
        cuadranteDescuidado: "Careless",
        cuadrantePeligro: "At Risk",
		chartCuadrantesTitulo: "Effort vs. Result Matrix",
    },
    pt: {
        estudiante: "Estudante:",
        logout: "Terminar sessão",
        bienvenidaTitulo: "Selecione um exercício",
        bienvenidaDesc: "Clique num exercício do menu lateral para ver as métricas e ativar o tutor IA.",
        btnResolver: "Resolver Exercício",
        dificultad: "Nível de dificuldade:",
        promedioNota: "Classificação média",
        promedioTiempo: "Tempo médio gasto",
        analiticas: "Analíticas do exercício",
        sinDatos: "Ainda não há dados suficientes para este exercício.",
        tituloChat: "Tutor IA",
        botSaludo: "Olá! Sou o teu tutor. Tens alguma dúvida sobre o conceito de '{concepto}'?",
        placeholderChat: "Escreve a tua dúvida...",
        btnEnviarChat: "Enviar",
        puntos: "pontos",
        puntajeMaximo: "Pontuação Máxima:",
        btnEnviarRespuesta: "Enviar Resposta",
        confirmarResolver: "Tens a certeza que queres resolver o exercício agora? Não poderás consultar as estatísticas nem pedir ajuda ao Tutor IA.",
        alertaSeleccion: "Por favor, seleciona uma opção antes de enviar.",
        alertaTexto: "Por favor, escreve o teu procedimento antes de enviar.",
        alertaExito: "Resposta guardada com sucesso!",
        alertaError: "Ocorreu um erro ao guardar a resposta. Tenta novamente.",
        enviando: "A enviar...",
        chartNotasTitulo: "Distribuição de Classificação",
        chartNotasY: "Nº de Estudantes",
        chartNotasX: "Classificação",
        chartExitoTitulo: "Taxa de Sucesso Global",
        chartAprobados: "Aprovados",
        chartSuspendidos: "Reprovados",
        chartTiempoTitulo: "Esforço vs Resultado (Tempo em mins vs Classificação)",
        chartTiempoX: "Tempo gasto (Segundos)",
        chartTiempoY: "Classificação obtida",
        tooltipTiempo: "Tempo",
        tooltipNota: "Classificação",
        difFacil: "Fácil",
        difMedio: "Médio",
        difDificil: "Difícil",
        placeholderCalculo: "Escreve aqui todo o teu procedimento passo a passo e o resultado final...",
		palabraEjercicio: "Exercício",
		labelInteraccion: "Interação do estudante",
		loginTitulo: "Entrar no Experimento",
        loginInstruccion: "Introduz o teu código de estudante:",
        loginPlaceholder: "Ex: 100456789",
        loginBoton: "Entrar",
        loginAlerta: "Por favor, introduz o teu código.",
		loginTituloPagina: "Login - Experiência Educativa",
		botPensando: "O tutor está a pensar...",
		labelJustificacion: "Justificação:",
        placeholderJustificacion: "Escreve brevemente por que escolheste esta opção...",
        alertaJustificacion: "Por favor, justifica a tua resposta antes de enviar.",
		cuadranteEficiente: "Eficiente",
        cuadrantePerseverante: "Perseverante",
        cuadranteDescuidado: "Descuidado",
        cuadrantePeligro: "Risco",
		chartCuadrantesTitulo: "Matriz de Esforço vs Resultado",
    }
};

function t(clave) {
    return Diccionario[AppConfig.idioma][clave] || clave;
}

function aplicarTextosGlobales() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const clave = el.getAttribute('data-i18n');
        if (el.tagName === 'INPUT' && el.type === 'text') {
            el.placeholder = t(clave);
        } else {
            el.innerText = t(clave);
        }
    });
}